# チャンキング設定ファイル
# 複数のチャンキング手法とそのパラメータを定義

chunking_methods:
  # 固定長トークンチャンキング
  token_based:
    type: "token_text_splitter"
    chunk_size: 512
    chunk_overlap: 50
    separator: "\n\n"
    backup_separators: ["\n", ".", " "]
    length_function: "len"
    add_start_index: true
    
  token_based_large:
    type: "token_text_splitter"
    chunk_size: 1024
    chunk_overlap: 100
    separator: "\n\n"
    backup_separators: ["\n", ".", " "]
    length_function: "len"
    add_start_index: true
    
  # セマンティックセグメント
  semantic_splitter:
    type: "semantic_splitter"
    buffer_size: 1
    breakpoint_percentile_threshold: 95
    embed_model: "sentence-transformers/all-MiniLM-L6-v2"
    
  # 見出しベースチャンキング
  markdown_header:
    type: "markdown_header_splitter"
    headers_to_split_on:
      - ["#", "Header 1"]
      - ["##", "Header 2"]  
      - ["###", "Header 3"]
    strip_headers: false
    return_each_line: false
    
  html_header:
    type: "html_header_splitter"
    headers_to_split_on:
      - ["h1", "Header 1"]
      - ["h2", "Header 2"]
      - ["h3", "Header 3"]
    return_each_element: false
    
  # 文書構造ベース
  sentence_splitter:
    type: "sentence_splitter"
    chunk_size: 1024
    chunk_overlap: 200
    paragraph_separator: "\n\n\n"
    chunking_tokenizer_fn: "tiktoken"
    tokenizer_kwargs:
      model_name: "gpt-3.5-turbo"
      
  # コードスプリッター（PDF内のコードブロック用）
  code_splitter:
    type: "code_splitter"
    language: "python"
    chunk_size: 500
    chunk_overlap: 50
    
  # レイアウトベース（PDF専用）
  layout_aware:
    type: "node_parser"
    parser_type: "simple_node_parser"
    text_splitter:
      type: "token_text_splitter"
      chunk_size: 512
      chunk_overlap: 50
    include_metadata: true
    include_prev_next_rel: true
    
# デフォルト設定
default_chunking:
  method: "token_based"
  
# 実験用設定パターン
experiment_patterns:
  pattern_1:
    name: "small_chunks"
    method: "token_based"
    chunk_size: 256
    chunk_overlap: 25
    
  pattern_2:
    name: "medium_chunks"  
    method: "token_based"
    chunk_size: 512
    chunk_overlap: 50
    
  pattern_3:
    name: "large_chunks"
    method: "token_based_large"
    chunk_size: 1024
    chunk_overlap: 100
    
  pattern_4:
    name: "semantic_chunks"
    method: "semantic_splitter"
    
  pattern_5:
    name: "sentence_chunks"
    method: "sentence_splitter"
    
  pattern_6:
    name: "markdown_structure"
    method: "markdown_header"

# メタデータ保持設定
metadata_settings:
  preserve_original: true
  add_chunk_info: true
  fields_to_preserve:
    - "source"
    - "page_number"
    - "document_title"
    - "section_title"
    - "chunk_index"
    - "total_chunks"
    - "file_path"
    - "created_at"
    - "chunk_method"

# 品質管理設定
quality_control:
  min_chunk_size: 10  # 最小チャンクサイズ（文字数）
  max_chunk_size: 2048  # 最大チャンクサイズ
  filter_empty_chunks: true
  remove_duplicate_chunks: true
  similarity_threshold: 0.95  # 重複判定閾値