# ドメイン固有設定ファイル
# 論文PDF・製品マニュアルPDFなど対象ドメインの設定

# データソース設定
data_sources:
  # 論文PDF設定
  research_papers:
    file_extensions: [".pdf"]
    expected_languages: ["ja", "en", "zh"]
    
    # 前処理設定
    preprocessing:
      extract_metadata: true
      extract_citations: true
      extract_figures_captions: true
      extract_tables: true
      preserve_formatting: true
      
    # メタデータ抽出設定
    metadata_extraction:
      title: true
      authors: true
      abstract: true
      keywords: true
      publication_date: true
      journal: true
      doi: true
      arxiv_id: true
      
    # 構造化要素
    structural_elements:
      abstract: true
      introduction: true
      methodology: true
      results: true
      conclusion: true
      references: true
      appendix: true
      
    # 専門用語処理
    domain_terminology:
      preserve_latex_equations: true
      extract_technical_terms: true
      normalize_symbols: false
      
  # 製品マニュアルPDF設定
  product_manuals:
    file_extensions: [".pdf"]
    expected_languages: ["ja", "en"]
    
    # 前処理設定
    preprocessing:
      extract_metadata: true
      extract_diagrams: true
      extract_step_by_step: true
      preserve_numbering: true
      
    # メタデータ抽出設定
    metadata_extraction:
      product_name: true
      version: true
      manufacturer: true
      model_number: true
      publication_date: true
      language: true
      
    # 構造化要素
    structural_elements:
      table_of_contents: true
      safety_warnings: true
      installation_steps: true
      operation_procedures: true
      troubleshooting: true
      specifications: true
      warranty_info: true
      
    # 専門用語処理
    domain_terminology:
      preserve_part_numbers: true
      extract_technical_specs: true
      normalize_units: true

# 言語設定
language_settings:
  # 日本語設定（優先）
  japanese:
    primary: true
    
    # 前処理
    text_preprocessing:
      normalize_unicode: "NFKC"
      remove_control_chars: true
      normalize_whitespace: true
      
    # トークナイゼーション
    tokenization:
      use_mecab: true
      mecab_dict: "ipadic"
      preserve_compounds: true
      
    # 文分割
    sentence_splitting:
      rules:
        - "。"
        - "！"
        - "？"
        - "．"
      preserve_parentheses: true
      
    # 専門用語処理
    terminology_handling:
      preserve_katakana_terms: true
      normalize_variants: false
      extract_compound_terms: true
      
  # 英語設定
  english:
    primary: false
    
    # 前処理
    text_preprocessing:
      normalize_unicode: "NFC"
      lowercase_normalization: false
      
    # トークナイゼーション
    tokenization:
      use_spacy: true
      spacy_model: "en_core_web_sm"
      
    # 文分割
    sentence_splitting:
      rules:
        - "."
        - "!"
        - "?"
      preserve_abbreviations: true
      
  # 多言語対応
  multilingual:
    auto_detection: true
    fallback_language: "japanese"
    
    # 言語検出
    language_detection:
      method: "langdetect"
      confidence_threshold: 0.8
      chunk_size: 1000

# PDF処理設定
pdf_processing:
  # 読み取りエンジン
  extraction_engines:
    primary: "pymupdf4llm"
    fallback: ["pymupdf", "pdfplumber", "pypdf2"]
    
  # レイアウト保持
  layout_preservation:
    maintain_columns: true
    preserve_tables: true
    extract_headers_footers: false
    merge_hyphenated_words: true
    
  # 図表処理
    figure_table_handling:
      extract_captions: true
      preserve_positioning: true
      ocr_for_images: false
      table_structure_detection: true
      
  # 品質管理
  quality_control:
    min_text_length: 10
    filter_noise: true
    encoding_detection: true
    corruption_detection: true

# チャンキング戦略（ドメイン特化）
domain_chunking:
  # 論文用チャンキング
  research_papers:
    strategy: "hierarchical"
    
    # 階層的分割
    hierarchy_levels:
      - section_headers  # セクション見出し
      - subsection_headers  # サブセクション
      - paragraphs  # 段落
      
    # セクション固有設定
    section_specific:
      abstract:
        chunk_size: 512
        preserve_complete: true
        
      introduction:
        chunk_size: 1024
        overlap: 100
        
      methodology:
        chunk_size: 1024
        preserve_steps: true
        
      results:
        chunk_size: 768
        include_tables: true
        
      conclusion:
        chunk_size: 512
        preserve_complete: true
        
  # マニュアル用チャンキング
  product_manuals:
    strategy: "procedural"
    
    # 手順重視分割
    procedural_splitting:
      preserve_step_sequences: true
      maintain_context: true
      
    # セクション固有設定
    section_specific:
      installation:
        chunk_size: 768
        preserve_order: true
        
      operation:
        chunk_size: 1024
        include_warnings: true
        
      troubleshooting:
        chunk_size: 512
        preserve_qa_pairs: true

# 評価設定（ドメイン特化）
domain_evaluation:
  # 論文用評価
  research_papers:
    focus_metrics:
      - "factual_accuracy"
      - "citation_relevance"
      - "technical_precision"
      
    specialized_checks:
      equation_handling: true
      terminology_consistency: true
      citation_verification: false
      
  # マニュアル用評価
  product_manuals:
    focus_metrics:
      - "procedural_accuracy"
      - "safety_compliance"
      - "completeness"
      
    specialized_checks:
      step_sequence_validation: true
      safety_warning_inclusion: true
      part_number_accuracy: true

# クエリパターン（ドメイン特化）
domain_query_patterns:
  # 論文関連クエリ
  research_papers:
    query_types:
      - "what_methodology"
      - "what_results"
      - "how_to_reproduce"
      - "what_limitations"
      - "related_work"
      
    example_queries:
      - "この研究の手法は何ですか？"
      - "実験結果はどうでしたか？"
      - "この手法の限界は何ですか？"
      
  # マニュアル関連クエリ
  product_manuals:
    query_types:
      - "how_to_install"
      - "how_to_operate"
      - "troubleshoot_problem"
      - "what_specifications"
      - "safety_precautions"
      
    example_queries:
      - "インストール方法を教えてください"
      - "この機能の使い方は？"
      - "エラーが出た時の対処法は？"

# 品質基準
quality_standards:
  # 論文品質基準
  research_papers:
    minimum_sections: ["title", "abstract", "conclusion"]
    required_elements: ["methodology", "results"]
    quality_indicators:
      has_citations: true
      has_figures: false
      min_pages: 3
      
  # マニュアル品質基準
  product_manuals:
    minimum_sections: ["overview", "installation", "operation"]
    required_elements: ["safety_warnings", "troubleshooting"]
    quality_indicators:
      has_diagrams: false
      has_step_numbers: true
      min_pages: 5

# ファイル管理設定
file_management:
  # 入力ファイル設定
  input:
    base_directory: "./data/raw"
    subdirectories:
      papers: "papers"
      manuals: "manuals"
      mixed: "mixed"
      
    file_validation:
      check_file_size: true
      max_file_size: "100MB"
      virus_scan: false
      
  # 出力ファイル設定
  output:
    base_directory: "./data/processed"
    preserve_structure: true
    backup_original: true
    
# ログ設定
logging:
  domain_specific_logs: true
  
  log_categories:
    pdf_processing: true
    metadata_extraction: true
    language_detection: true
    chunking_analysis: true
    
  log_levels:
    pdf_processing: "INFO"
    metadata_extraction: "DEBUG"
    language_detection: "WARNING"

# パフォーマンス設定
performance:
  # PDF処理パフォーマンス
  pdf_processing:
    parallel_processing: true
    max_workers: 4
    memory_limit: "2GB"
    
  # チャンキングパフォーマンス
  chunking:
    batch_processing: true
    cache_intermediate_results: true
    
# セキュリティ設定
security:
  # 機密データ処理
  confidential_data:
    anonymization: false
    redaction_patterns: []
    access_logging: true
    
  # ファイルセキュリティ
  file_security:
    scan_for_malware: false
    validate_pdf_structure: true
    quarantine_suspicious: false