# 埋め込みモデル設定ファイル
# 複数のembeddingバックエンドとモデルを定義

embedding_models:
  # Ollama系 (ローカル推論)
  ollama_qwen3:
    backend: "ollama"
    model_name: "qwen3-embedding:8b"
    base_url: "http://localhost:11434"
    dimensions: 1536
    max_tokens: 8192
    batch_size: 32
    timeout: 60
    
  ollama_nomic:
    backend: "ollama" 
    model_name: "nomic-embed-text"
    base_url: "http://localhost:11434"
    dimensions: 768
    max_tokens: 2048
    batch_size: 64
    timeout: 30
    
  # Sentence Transformers
  sentence_transformers_multilingual:
    backend: "sentence_transformers"
    model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    dimensions: 384
    device: "auto"  # cpu, cuda, auto
    normalize_embeddings: true
    batch_size: 32
    
  sentence_transformers_japanese:
    backend: "sentence_transformers" 
    model_name: "sentence-transformers/distiluse-base-multilingual-cased"
    dimensions: 512
    device: "auto"
    normalize_embeddings: true
    batch_size: 32
    
  sentence_transformers_large:
    backend: "sentence_transformers"
    model_name: "sentence-transformers/all-mpnet-base-v2"
    dimensions: 768
    device: "auto"
    normalize_embeddings: true
    batch_size: 16
    
  # OpenAI (API)
  openai_ada002:
    backend: "openai"
    model_name: "text-embedding-ada-002"
    api_key: "${OPENAI_API_KEY}"
    dimensions: 1536
    batch_size: 100
    max_retries: 3
    timeout: 30
    
  openai_3_small:
    backend: "openai"
    model_name: "text-embedding-3-small"
    api_key: "${OPENAI_API_KEY}"
    dimensions: 1536
    batch_size: 100
    max_retries: 3
    timeout: 30
    
  openai_3_large:
    backend: "openai"
    model_name: "text-embedding-3-large"
    api_key: "${OPENAI_API_KEY}"
    dimensions: 3072
    batch_size: 50
    max_retries: 3
    timeout: 60
    
  # HuggingFace Transformers (ローカル)
  huggingface_multilingual:
    backend: "huggingface"
    model_name: "intfloat/multilingual-e5-large"
    dimensions: 1024
    device: "auto"
    trust_remote_code: false
    batch_size: 16
    
  # Cohere (API)
  cohere_multilingual:
    backend: "cohere"
    model_name: "embed-multilingual-v3.0"
    api_key: "${COHERE_API_KEY}"
    dimensions: 1024
    input_type: "search_document"
    batch_size: 96
    
# バックエンド固有設定
backend_configs:
  ollama:
    connection_timeout: 30
    read_timeout: 300
    max_retries: 3
    retry_delay: 1.0
    
  sentence_transformers:
    cache_folder: "./models/sentence_transformers"
    local_files_only: false
    trust_remote_code: false
    
  openai:
    organization: null
    max_retries: 3
    request_timeout: 30
    
  huggingface:
    cache_dir: "./models/huggingface"
    trust_remote_code: false
    use_auth_token: false
    
  cohere:
    max_retries: 3
    timeout: 30

# デフォルト設定
default_embedding:
  model: "ollama_qwen3"
  
# 実験用パターン
experiment_patterns:
  pattern_1:
    name: "ollama_local"
    model: "ollama_qwen3"
    
  pattern_2:
    name: "sentence_transformers_fast"
    model: "sentence_transformers_multilingual"
    
  pattern_3:
    name: "sentence_transformers_accurate"
    model: "sentence_transformers_large"
    
  pattern_4:
    name: "openai_standard"
    model: "openai_ada002"
    
  pattern_5:
    name: "openai_latest"
    model: "openai_3_small"
    
  pattern_6:
    name: "multilingual_focus"
    model: "huggingface_multilingual"

# バッチ処理設定
batch_processing:
  default_batch_size: 32
  max_batch_size: 100
  adaptive_batching: true
  memory_threshold: 0.8  # GPU/CPUメモリ使用率閾値
  
# キャッシュ設定
caching:
  enabled: true
  cache_dir: "./cache/embeddings"
  cache_ttl: 86400  # 24時間 (秒)
  max_cache_size: "1GB"
  compression: true
  
# 並列処理設定
parallel_processing:
  enabled: true
  max_workers: 4
  chunk_size_per_worker: 50
  
# 品質管理
quality_control:
  validate_dimensions: true
  check_nan_values: true
  normalize_vectors: true
  dimension_tolerance: 0  # 次元数の許容誤差
  
# 言語固有設定
language_specific:
  japanese:
    preferred_models:
      - "sentence_transformers_japanese"
      - "huggingface_multilingual"
    text_preprocessing:
      normalize_unicode: true
      remove_control_chars: true
      
  multilingual:
    preferred_models:
      - "sentence_transformers_multilingual"
      - "huggingface_multilingual"
      - "cohere_multilingual"