version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/example

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"

  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus_db
    ports:
      - "19530:19530"
      - "19121:19121"
    environment:
      MILVUS_DB: milvus

volumes:
  mongo_data: